export const ADDING_CHANNEL_START = "ADDING_CHANNEL_START";
export const ADDING_CHANNEL_SUCCESS = "ADDING_CHANNEL_SUCCESS";
export const ADDING_CHANNEL_FAILED = "ADDING_CHANNEL_FAILED";
export const FETCHING_CHANNEL_START = "FETCHING_CHANNEL_START";
export const FETCHING_CHANNEL_SUCCESS = "FETCHING_CHANNEL_SUCCESS";
export const FETCHING_CHANNEL_FAILED = "FETCHING_CHANNEL_FAILED";
export const FETCHING_INDIVIDUAL_CHANNEL = "FETCHING_INDIVIDUAL_CHANNEL";
