export const ADDING_CHANNEL_START = "ADDING_CHANNEL_START";
export const ADDING_CHANNEL_SUCCESS = "ADDING_CHANNEL_SUCCESS";
export const ADDING_CHANNEL_FAILURE = "ADDING_CHANNEL_FAILURE";
export const GET_CHANNEL_START = "GET_CHANNEL_START";
export const GET_CHANNEL_SUCCESS = "GET_CHANNEL_SUCCESS";
export const GET_CHANNEL_FAILURE = "GET_CHANNEL_FAILURE";
export const GET_INDIVIDUAL_CHANNEL = "GET_INDIVIDUAL_CHANNEL";
